# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class Brand:
    id: Any
    name: Any
    abbv: Any


@dataclasses.dataclass()
class SkuMap:
    id: Any
    supplier: Any
    spn: Any
    sku: Any


@dataclasses.dataclass()
class Supplier:
    id: Any
    name: Any
    brand: Optional[Any]


@dataclasses.dataclass()
class Uom:
    id: Any
    supplier: Any
    sku: Any
    unit: Any
    amount: Any
